config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('veterinary.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

veterinary/urls.py
from django.contrib import admin
from django.urls import path
from veterinary.views import OwnerView
from veterinary.views import( InsertOwnerView,EditOwnerView,InsertAnimalView,AnimalView,EditAnimalView,
AnimalDeteailView ,AnimalDeleteView,OwnerDeleteView)

app_name="veterinary"
urlpatterns = [

    path('', OwnerView.as_view(),name="owner"),#Home page
    path('insertowner',InsertOwnerView.as_view(),name="insertowner"),
    path('editowner/<slug:slug>',EditOwnerView.as_view(),name="editowner"),
    path('animal/<slug:slug>',AnimalView.as_view(),name="animal"),
    path('insertanimal/<slug:slug>',InsertAnimalView.as_view(),name="insertanimal"),
    path('editanimal/<slug:slug>',EditAnimalView.as_view(),name="editanimal"),
    path('detailanimal/<slug:slug>',AnimalDeteailView.as_view(),name="detailanimal"),
    path('deleteowner/<slug:slug>',AnimalDeleteView.as_view(),name="animaldelete"),
    path('deleteanimal/<slug:slug>',OwnerDeleteView.as_view(),name="ownerdelete"),

    
]

veterinary/models/Animal.py
from django.db import models
from autoslug import AutoSlugField
from .Owner import OwnerModel
class AnimalModel(models.Model):
    owner=models.ForeignKey(OwnerModel,on_delete=models.CASCADE,related_name="owner",null=True)
    kind= models.CharField(max_length=50,null=True)
    genus= models.CharField(max_length=50,null=True)
    name= models.CharField(max_length=70,null=True)
    slug = AutoSlugField(populate_from='name')
    age=models.IntegerField(blank=True,unique=False)
    description=models.TextField(unique=False,null=False)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)
 
    class Meta:
        verbose_name="Animal"
        verbose_name = 'Animal'
      
    def __str__(self):
        return self.name

veterinary/models/Owner.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User
class OwnerModel(models.Model):
    user = models.ForeignKey('accounts.CustomUserModel',on_delete=models.CASCADE,related_name="user",null=True)
    name= models.CharField(max_length=50,null=True)
    slug = AutoSlugField(populate_from='name')
    email=models.EmailField(max_length=70,blank=True,unique=True)
    phone = models.CharField(max_length=17, unique=False)
    address=models.TextField(unique=False,null=False)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)

 
    class Meta:
        verbose_name="Owner"
        verbose_name = 'Owner'

    def __str__(self):
        return self.name

veterinary/forms/insertanimal.py
from django import forms
from veterinary.models import AnimalModel
from django.utils.translation import gettext_lazy as _
class NewAnimalForm(forms.ModelForm):

	class Meta:
		model = AnimalModel
		fields = ("kind", "genus", "name", "age","description",)
		labels={"kind":"Tür","genus":"Cins","name":"İsim","age":"Yaş","description":"Açıklama"}
       
     

veterinary/forms/insertowner.py
from django import forms
from veterinary.models import OwnerModel
from django.contrib import messages
class NewOwnerForm(forms.ModelForm):
   
	class Meta:
		model = OwnerModel
		fields = ("name", "email", "phone", "address")
		labels={"name":"İsim","email":"Email","phone":"Telefon","adsress":"Adres"}
	def save(self, commit=True):
		user = super(NewOwnerForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

veterinary/views.py
from django.shortcuts import render

# Create your views here.

veterinary/views/animal.py
from multiprocessing import context
from django.shortcuts import render
from django.views import View
from veterinary.models import OwnerModel,AnimalModel
from django.contrib.auth.mixins import LoginRequiredMixin

class AnimalView(LoginRequiredMixin,View):
    
    http_method_names=['get','post']
    def get(self,request,slug):
        search=request.GET.get('search')
        
        owner=OwnerModel.objects.get(slug=slug)
        context={ 
            "animal":AnimalModel.objects.filter(owner=owner),
            "owner":OwnerModel.objects.filter(slug=slug)[:1].get()
        }
        
        return render(request,'page/animal.html',context=context)

veterinary/views/deleteanimal.py
from django.views.generic import DeleteView
from veterinary.models import AnimalModel
from django.shortcuts import get_object_or_404,redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

class AnimalDeleteView(LoginRequiredMixin, DeleteView):
    template_name='page/deleteconfirm.html'
    success_url = reverse_lazy("veterinary:owner")
    def get_queryset(self):
       animal=AnimalModel.objects.filter(slug=self.kwargs.get("slug"))
       return animal

veterinary/views/deleteowner.py
from django.views.generic import DeleteView
from veterinary.models import OwnerModel
from django.shortcuts import get_object_or_404,redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

class OwnerDeleteView(LoginRequiredMixin, DeleteView):
    template_name='page/deleteconfirm.html'
    success_url = reverse_lazy("veterinary:owner")
    def get_queryset(self):
       
       owner=OwnerModel.objects.filter(slug=self.kwargs.get("slug"))
       return owner

veterinary/views/detailanimal.py
from django.views.generic import DetailView 
from django.shortcuts import get_object_or_404
from veterinary.models import AnimalModel
from django.contrib.auth.mixins import LoginRequiredMixin

class AnimalDeteailView(LoginRequiredMixin, DetailView):

    template_name='page/detail_animal.html'
    context_object_name='animal'
    def get_object(self):
        return get_object_or_404(
            AnimalModel,slug=self.kwargs.get("slug")
        )
    

veterinary/views/editanimal.py
from multiprocessing import context
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from veterinary.models import AnimalModel,OwnerModel
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from veterinary.forms import NewAnimalForm
class EditAnimalView(LoginRequiredMixin,View):
    
    http_method_names=['get','post']

    def get(self,request,slug):
        animal=get_object_or_404(AnimalModel,slug=slug)
        form=NewAnimalForm(instance=animal)
        
        context={ 
            "edit_form":form
        }
        
        return render(request,'page/edit_animal.html',context=context)

    def post(self,request,slug):
               animal=get_object_or_404(AnimalModel,slug=slug)
               owner=OwnerModel.objects.get(owner=animal)
               form=NewAnimalForm(request.POST or None,instance=animal)
               if form.is_valid():
                   form.save()
                   messages.success(self.request, "Hayvan  Güncellendi. " )
                   return redirect("veterinary:animal",slug=owner.slug)
           
               else:
                    messages.success(self.request, "Hayvan  Güncellenemedi. " )
                    return redirect("veterinary:editowner",slug=owner.slug)
       
          

veterinary/views/editowner.py
from multiprocessing import context
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from veterinary.models import OwnerModel
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from veterinary.forms import NewOwnerForm
class EditOwnerView(LoginRequiredMixin,View):
    
    http_method_names=['get','post']

    def get(self,request,slug):
        owner=get_object_or_404(OwnerModel,slug=slug,user=request.user)
        form=NewOwnerForm(instance=owner)
        
        context={ 
            "edit_form":form
        }
        
        return render(request,'page/edit_owner.html',context=context)

    def post(self,request,slug):
               owner=get_object_or_404(OwnerModel,slug=slug,user=request.user)
               form=NewOwnerForm(request.POST or None,instance=owner)
               if form.is_valid():
                   form.save()
                   messages.success(self.request, "Hayvan sahibi Güncellendi. " )
                   return redirect("veterinary:owner")
           
               else:
                    messages.success(self.request, "Hayvan sahibi Güncellenemedi. " )
                    return redirect("veterinary:editowner",slug=slug)
       
          

veterinary/views/insertanimal.py
from multiprocessing import context
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from veterinary.models import AnimalModel,OwnerModel
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from veterinary.forms import NewAnimalForm
class InsertAnimalView(LoginRequiredMixin,View):
  
    
    http_method_names=['get','post']

    def get(self,request,slug):
        
       
        form=NewAnimalForm() 
        
        context={ 
            "insert_form":form
        }
        
        return render(request,'page/insert_animal.html',context=context)

    def post(self,request,slug):
        owner=OwnerModel.objects.get(slug=slug)
        form=NewAnimalForm(request.POST)
        if form.is_valid():
          animal = form.save(commit=False)
          animal.owner=owner
          animal.save()
          messages.success(self.request, "Hayvan  Eklendi." )
          return redirect("veterinary:animal",slug=owner.slug)
           
        else:
            messages.success(self.request, "Hayvan  Eklenemedi." )
            return redirect("veterinary:insertowner")
       
          
          

veterinary/views/insertowner.py
from multiprocessing import context
from django.shortcuts import render,redirect
from django.views import View
from veterinary.models import OwnerModel
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from veterinary.forms import NewOwnerForm

class InsertOwnerView(LoginRequiredMixin,View):
    
    http_method_names=['get','post']
    form = NewOwnerForm()
    def get(self,request):
        context={ 
            "insert_form":self.form
        }
        
        return render(request,'page/insert_owner.html',context=context)

    def post(self,request):
        form=NewOwnerForm(request.POST)
        if form.is_valid():
            owner = form.save(commit=False)
            owner.user=request.user
            owner.save()
            messages.success(self.request, "Hayvan sahibi Eklendi." )
            return redirect("veterinary:owner")
           
        else:
            messages.success(self.request, "Hayvan sahibi Eklenemedi." )
            return redirect("veterinary:insertowner")
       
          

veterinary/views/owner.py
from multiprocessing import context
from django.shortcuts import render
from django.views import View
from veterinary.models import OwnerModel,AnimalModel
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
class OwnerView(LoginRequiredMixin,View):
    
    http_method_names=['get','post']
    def get(self,request):
        search=request.GET.get('search')
        owner=OwnerModel.objects.filter(user=request.user)
        if search:
            owner= owner.filter(
                Q(name__icontains=search) 
            )
           

        context={ 
            "owner":owner
        }
        
        return render(request,'page/owner.html',context=context)

veterinary/templates/page/animal.html
{% extends 'layout.html' %}
{% block title %} Hayvanlar {% endblock %}

{% block content %}


{% if messages %}
<ul class="messages">
    {% for message in messages %}

    <div {% if message.tags %} class="alert alert-success {{ message.tags }}" {% endif %} role="alert">
        {{message}}
    </div>
    {% endfor %}
</ul>
{% endif %}
<div class="row ">
    <div class="col-sm-12">
        <div class="col-xl-12">

            <div class="card mb-4 mb-xl-0">
                <div class="card-header">Sahib Bilgisi</div>
                <div class="card-body text-center">
                    <form>

                        <div class="mb-3">
                            <label class="small mb-1">Adı</label>
                            <input class="form-control" type="text" readonly value="{{owner.name}}">
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1">Email</label>
                            <input class="form-control" type="text" readonly value="{{owner.email}}">
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1">Telefon</label>
                            <input class="form-control" type="text" readonly value="{{owner.phone}}">
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1">Adres</label>
                            <textarea class="form-control" type="text" readonly> {{owner.address}}</textarea>
                        </div>


                    </form>



                </div>
            </div>
        </div>

    </div>

</div>

<div class="container-fuild mt-3">
    <div class="row">



        <div class="col-md-12 ">

            <div class="panel panel-default panel-table">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col col-xs-6">
                            <h3 class="panel-title">Sahip olduğu hayvanlar</h3>
                        </div>
                        <div class="col col-xs-6 text-right">
                            <a href="{% url 'veterinary:insertanimal' slug=owner.slug %}" class=" btn btn-sm btn-primary
                                btn-create">Yeni Ekle</a>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-list">
                        <thead>
                            <tr>
                                <th><em class="fa fa-cog"></em></th>
                                <th scope="col">Tür</th>
                                <th scope="col">Cins</th>
                                <th scope="col">İsim</th>
                                <th scope="col">Yaş</th>
                            </tr>
                        </thead>
                     
                        <tbody>
                            {% for row in animal  %}
                            <tr>
                                <td align="center">
                                    <a href="{% url 'veterinary:editanimal' slug=row.slug %}"
                                        class="btn btn-primary">Düzenle</a>
                                    <a href="{% url 'veterinary:detailanimal' slug=row.slug %}"
                                    
                                        class="btn btn-info">Detay</a>
                                        {% if user.role %}
                                    <a href="{% url 'veterinary:animaldelete' slug=row.slug %}"
                                        class="btn btn-danger">Sil</a>
                                        {% endif %}
                                </td>
                                <td> {{row.kind}}</td>
                                <td> {{row.genus}}</td>
                                <td> {{row.name}} </td>
                                <td> {{row.age}} </td>
                            </tr>
                            {%  endfor %}

                        </tbody>
                    </table>

                </div>

            </div>

        </div>
    </div>
</div>
{% endblock %}

veterinary/templates/page/deleteconfirm.html
{% extends 'layout.html' %}
{% block title %} Silmek İstediğinize Eminmisiniz {% endblock %}

{% block content %}





<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            Öğeyi Sil
        </div>
        <div class="modal-body">
            Silmek İstediğinizden Eminmisiniz
        </div>
        <div class="modal-footer">
            <a href="{{request.META.HTTP_REFERER}}" class="btn btn-info" data-dismiss="modal">Hayır</a>
            <form method="POST">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Evet" />
            </form>
        </div>
    </div>
</div>

{% endblock %}

veterinary/templates/page/detail_animal.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} Hayvan Detay {% endblock %}

{% block content %} 

  <div class="container-xl px-4 mt-4">
    <hr class="mt-0 mb-4">
    <div class="row">
        <div class="col-xl-4">
  
            <div class="card mb-4 mb-xl-0">
                <div class="card-header">Sahib Bilgisi</div>
                <div class="card-body text-center">
                    <form>
                   
                        <div class="mb-3">
                            <label class="small mb-1" >Adı</label>
                            <input class="form-control"  type="text"  readonly  value="{{animal.owner.name}}">
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" >Email</label>
                            <input class="form-control"  type="text"  readonly  value="{{animal.owner.email}}">
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" >Telefon</label>
                            <input class="form-control"  type="text"  readonly  value="{{animal.owner.phone}}">
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" >Adres</label>
                            <textarea class="form-control"  type="text"  readonly  > {{animal.owner.address}}</textarea>
                        </div>
                     
                    </form>
                  
              
                </div>
            </div>
        </div>
        <div class="col-xl-8">
      
            <div class="card mb-4">
                <div class="card-header">Hayvan Detay</div>
                <div class="card-body">
                    <form>
                   
                        <div class="mb-3">
                            <label class="small mb-1" >Adı</label>
                            <input class="form-control"  type="text"  readonly  value="{{animal.name}}">
                        </div>
               
                        <div class="row gx-3 mb-3">
                     
                            <div class="col-md-6">
                                <label class="small mb-1" >Tür</label>
                                <input class="form-control"  type="text" readonly value="{{animal.kind}}">
                            </div>
                   
                            <div class="col-md-6">
                                <label class="small mb-1">Cins</label>
                                <input class="form-control"type="text" readonly value="{{animal.genus}}">
                            </div>
                        </div>
                      
                        <div class="row gx-3 mb-3">
                         
                            <div class="col-md-12">
                                <label class="small mb-1">Yaş </label>
                                <input class="form-control"  readonly type="text"  value="{{animal.age}}">
                            </div>
                         
                        </div>
              
                        <div class="mb-3">
                            <label class="small mb-1" >Açıklama</label>
                            <textarea class="form-control"  type="email" readonly > {{animal.description}} </textarea>
                        </div>
                 
                     
           
                    
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

veterinary/templates/page/edit_animal.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} Hayvan Güncelle {% endblock %}

{% block content %} 


 

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Hayvan  Güncelle</li>
    </ol>
  </nav>
<main class="login-form mt-5">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                 
                    <div class="card-body text-center">
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            
                            <div {% if message.tags %}  class="alert alert-danger {{ message.tags }}" {% endif %} role="alert">
                            {{message}}
                              </div>
                                {% endfor %}
                        </ul>
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            {{ edit_form|crispy }}
                            <button type="submit" class="btn btn-primary mt-3">
                              Güncelle
                            </button>
                          
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>

{% endblock %}

veterinary/templates/page/edit_owner.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} Hayvan Sahibi Güncelle {% endblock %}

{% block content %} 


 

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Hayvan Sahibi Güncelle</li>
    </ol>
  </nav>
<main class="login-form mt-5">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                 
                    <div class="card-body text-center">
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            
                            <div {% if message.tags %}  class="alert alert-danger {{ message.tags }}" {% endif %} role="alert">
                            {{message}}
                              </div>
                                {% endfor %}
                        </ul>
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            {{ edit_form|crispy }}
                            <button type="submit" class="btn btn-primary mt-3">
                              Güncelle
                            </button>
                          
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>

{% endblock %}

veterinary/templates/page/insert_animal.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} Hayvan Sahibi Ekle {% endblock %}

{% block content %} 


 

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Hayvan Sahibi Ekle</li>
    </ol>
  </nav>
<main class="login-form mt-5">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                 
                    <div class="card-body text-center">
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            
                            <div {% if message.tags %}  class="alert alert-success {{ message.tags }}" {% endif %} role="alert">
                            {{message}}
                              </div>
                                {% endfor %}
                        </ul>
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            {{ insert_form|crispy }}
                            <button type="submit" class="btn btn-primary mt-3">
                              Ekle
                            </button>
                          
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>

{% endblock %}

veterinary/templates/page/insert_owner.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} Hayvan Sahibi Ekle {% endblock %}

{% block content %} 


 

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">Hayvan Sahibi Ekle</li>
    </ol>
  </nav>
<main class="login-form mt-5">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                 
                    <div class="card-body text-center">
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            
                            <div {% if message.tags %}  class="alert alert-success {{ message.tags }}" {% endif %} role="alert">
                            {{message}}
                              </div>
                                {% endfor %}
                        </ul>
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            {{ insert_form|crispy }}
                            <button type="submit" class="btn btn-primary mt-3">
                              Ekle
                            </button>
                          
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>

{% endblock %}

veterinary/templates/page/owner.html
{% extends 'layout.html' %}
{% block title %} Anasayfa {% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
  {% for message in messages %}

  <div {% if message.tags %} class="alert alert-success {{ message.tags }}" {% endif %} role="alert">
    {{message}}
  </div>
  {% endfor %}
</ul>
{% endif %}

<div class="container-fuild">
  <div class="row">

  

    <div class="col-md-12 ">

      <div class="panel panel-default panel-table">
        <div class="panel-heading">
          <div class="row">
            <div class="col col-xs-6">
              <h3 class="panel-title">Havyan Sahibleri</h3>
            </div>
            <div class="col col-xs-6 text-right">
              <a href="{% url 'veterinary:insertowner' %} "  class="btn btn-sm btn-primary btn-create">Yeni Ekle</a>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <table class="table table-striped table-bordered table-list">
            <thead>
              <tr>
                <th><em class="fa fa-cog"></em></th>
                <th class="hidden-xs">ID</th>
                <th scope="col">İsim</th>
                <th scope="col">E-Poste</th>
                <th scope="col">Telefon</th>
              </tr>
            </thead>
            <tbody>
              {% for row in owner  %}
              <tr>
                <td align="center">
                  <a href="{% url 'veterinary:editowner' slug=row.slug %}" class="btn btn-primary">Düzenle</a>
                  <a href="{% url 'veterinary:insertanimal' slug=row.slug %}" class="btn btn-success">Hayvan Ekle</a>
                  <a href="{% url 'veterinary:animal' slug=row.slug %}" class="btn btn-info">Hayvanlar</a>
                  {% if user.role %}
                  <a href="{% url 'veterinary:ownerdelete' slug=row.slug %}" class="btn btn-danger">Sil</a>
                  {% endif %}
                </td>
                <td class="hidden-xs"> {{row.id}} </td>
                <td>{{row.name}}</td>
                <td>{{ row.email}}</td>
                <td> {{row.phone}} </td>
              </tr>
              {%  endfor %}
            </tbody>
          </table>

        </div>
        
      </div>

    </div>
  </div>
</div>

{% endblock %}