config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('veterinary.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

veterinary/urls.py
from django.contrib import admin
from django.urls import path
from veterinary.views import OwnerView
from veterinary.views import( InsertOwnerView,EditOwnerView,InsertAnimalView,AnimalView,EditAnimalView,
AnimalDeteailView ,AnimalDeleteView,OwnerDeleteView)

app_name="veterinary"
urlpatterns = [

    path('', OwnerView.as_view(),name="owner"),#Home page
    path('insertowner',InsertOwnerView.as_view(),name="insertowner"),
    path('editowner/<slug:slug>',EditOwnerView.as_view(),name="editowner"),
    path('animal/<slug:slug>',AnimalView.as_view(),name="animal"),
    path('insertanimal/<slug:slug>',InsertAnimalView.as_view(),name="insertanimal"),
    path('editanimal/<slug:slug>',EditAnimalView.as_view(),name="editanimal"),
    path('detailanimal/<slug:slug>',AnimalDeteailView.as_view(),name="detailanimal"),
    path('deleteowner/<slug:slug>',AnimalDeleteView.as_view(),name="animaldelete"),
    path('deleteanimal/<slug:slug>',OwnerDeleteView.as_view(),name="ownerdelete"),

    
]

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'veterinary:owner' %}">Hayvan Sahipleri</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'veterinary:insertowner' %}">Hayvan Sahibi Ekle</a>
                </li>
          
              
                
            </ul>
            <form action="{% url 'veterinary:owner' %}" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" name="search"  placeholder="Ara" aria-label="Search">
                <button class="btn btn-outline-success mr-2 my-2 my-sm-0"  type="submit">Ara</button>
            </form>
            {% endif %}
            {% if user.is_authenticated %}
            <a href="/accounts/logout/"  class="btn btn-outline-success my-2 mr-2 my-sm-0" type="submit">Çıkış Yap</a>
          
            {% endif %}
            
        </div>
    </nav>

    <div class="container-fuild">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% block js %}{% endblock %}

</body>

</html>